### ISSUE TITLE
Composer/README Updates Part 2

### ISSUE THREAD

**Issue by bd-viget** [vigetlabs/wordpress-site-starter#50]
# Summary

This task is to fix a few straggling issues with the Composer Script, and integrate the theme scripts (`bin/start`) with the Composer `post-install` commands.

## Tasks

- [ ] Fix bug where `post-create-project` script runs after `post-install` command.
- [ ] Run theme `composer install`
- [ ] Change `ddev start` to `bin/start`
- [ ] Updates to `README.dist.md`
- [ ] Swap `README.md` with `README.dist.md`
- [ ] Remove `packages.json`
